//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_RAAMEN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Headerid { get; set; }
        public int Ramenid { get; set; }
        public int Quantity { get; set; }
    
        public virtual Header Header { get; set; }
        public virtual Ramen Raman { get; set; }
    }
}
